config/routes.rb
Rails.application.routes.draw do

  resources :users, except: :index
  resources :investors


  get '/login', to: "sessions#login"
  post '/sessions', to: "sessions#create"
  delete 'logout', to: "sessions#logout"
  root "startup#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/investor.rb
class Investor < ApplicationRecord
  belongs_to :user 
  has_many_attached :files

  validates :first_name, presence: true, length: {minimum: 2}
  validates :last_name, presence: true, length: {minimum: 2}
  validates :dob, presence: true, if: :dob_is_date?
  validates :phone, presence: true
  validates_format_of :phone, :with => /[0-9]{3}-[0-9]{3}-[0-9]{4}/, :message => "Phone numbers must be in xxx-xxx-xxxx format."
  validates :street_address, presence: true
  validates :state_address, presence: true, length: {is: 2}, format: { with: /\A[a-zA-Z]+\z/,
    message: "only allows letters" }
  validates :zip_code, presence: true, length: { is: 5}

  private

  def dob_is_date?
    if !dob.is_a?(Time)
      errors.add(:dob, "Must be a valid date.")
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :investors, dependent: :destroy

  validates :username, presence: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authorize

    def authorize
      if !User.find_by(id: session[:user_id])
      end
    end
end

app/controllers/investors_controller.rb
class InvestorsController < ApplicationController
  before_action :set_investor, only: [:show, :edit, :update, :destroy]

  # GET /investors
  # GET /investors.json
  def index
    @user = User.find_by(id: session[:user_id])
    @investors = @user.investors
  end

  # GET /investors/1
  # GET /investors/1.json
  def show
  end

  # GET /investors/new
  def new
    @investor = Investor.new
  end

  # GET /investors/1/edit
  def edit
  end

  # POST /investors
  # POST /investors.json
  def create
    @investor = Investor.new(investor_params)

    respond_to do |format|
      if @investor.save
        format.html { redirect_to @investor, notice: 'Investor was successfully created.' }
        format.json { render :show, status: :created, location: @investor }
      else
        format.html { render :new }
        format.json { render json: @investor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /investors/1
  # PATCH/PUT /investors/1.json
  def update
    respond_to do |format|
      if @investor.update(investor_params)
        format.html { redirect_to @investor, notice: 'Investor was successfully updated.' }
        format.json { render :show, status: :ok, location: @investor }
      else
        format.html { render :edit }
        format.json { render json: @investor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /investors/1
  # DELETE /investors/1.json
  def destroy
    @investor.destroy
    respond_to do |format|
      format.html { redirect_to investors_url, notice: 'Investor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_investor
      @investor = Investor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def investor_params
      params.require(:investor).permit(:first_name, :last_name, :dob, :phone, :street_address, :state_address, :zip_code, :user_id, files: [])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorize, only: [:login, :create]

  def login
  end

  def create
    @user = User.find_by(username: params[:username])
    if !!@user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:unauthenticated] = "Not Authenticated"
      redirect_to login_path
    end
  end

  def logout
    session.delete(:user_id)
    redirect_to login_path
  end
end

app/controllers/sessons_controller.rb
class SessonsController < ApplicationController
  skip_before_action :authorize, only: [:login, :create]


  def create
    @user = User.find_by(username: params[:username])
    if !!@user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:unauthenticated] = "Not Authenticated"
      redirect_to login_path
    end
  end

  def logout
    session.delete(:user_id)
    redirect_to login_path
  end
end

app/controllers/startup_controller.rb
class StartupController < ApplicationController
  
  def index
    @user = User.find_by(id: session[:user_id])
    if !!@user
      redirect_to user_path(@user)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :destroy]

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    unless session[:user_id] == @user.id
      flash[:notice] = "You don't have access to that User!"
      redirect_to user_path(session[:user_id])
      return
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    session[:user_id] = nil
    respond_to do |format|
      format.html { redirect_to '/home', notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/investors_helper.rb
module InvestorsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/sessons_helper.rb
module SessonsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/investors/_form.html.erb
<%= form_with(model: investor, local: true) do |form| %>
  <% if investor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(investor.errors.count, "error") %> prohibited this investor from being saved:</h2>

      <ul>
      <% investor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :user_id, :value => session[:user_id] %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :date_of_birth %>
    <%= form.date_select :dob, :start_year=>1930, :end_year=>2015 %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :street_address %>
    <%= form.text_field :street_address %>
  </div>

  <div class="field">
    <%= form.label :state_address %>
    <%= form.text_field :state_address %>
  </div>

  <div class="field">
    <%= form.label :zip_code %>
    <%= form.text_field :zip_code %>
  </div>

  <div class="field">
  <%= form.label :files %>
  <%= form.file_field :files, multiple: true, direct_upload: true %>
</div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/investors/edit.html.erb
<h1>Editing Investor</h1>

<%= render 'form', investor: @investor %>

<%= link_to 'Back to Investor Show', @investor %> |
<%= link_to 'Back to All Investors', investors_path %> | <%= link_to "Log out", logout_path, method: :delete %> 

app/views/investors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Investors</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Dob</th>
      <th>Phone</th>
      <th>Street address</th>
      <th>State address</th>
      <th>Zip code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @investors.each do |investor| %>
      <tr>
        <td><%= investor.first_name %></td>
        <td><%= investor.last_name %></td>
        <td><%= investor.dob %></td>
        <td><%= investor.phone %></td>
        <td><%= investor.street_address %></td>
        <td><%= investor.state_address %></td>
        <td><%= investor.zip_code %></td>
        <td><%= link_to 'Show', investor %></td>
        <td><%= link_to 'Edit', edit_investor_path(investor) %></td>
        <td><%= link_to 'Destroy', investor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Your User', user_path(@user) %> | <%= link_to 'New Investor', new_investor_path %> | <%= link_to "Log out", logout_path, method: :delete %> 

app/views/investors/new.html.erb
<h1>New Investor</h1>

<%= render 'form', investor: @investor %>

<%= link_to 'Back to All Your Investors', investors_path %> | <%= link_to "Log out", logout_path, method: :delete %> 

app/views/investors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @investor.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @investor.last_name %>
</p>

<p>
  <strong>Date of Birth:</strong>
  <%= @investor.dob %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @investor.phone %>
</p>

<p>
  <strong>Street address:</strong>
  <%= @investor.street_address %>
</p>

<p>
  <strong>State address:</strong>
  <%= @investor.state_address %>
</p>

<p>
  <strong>Zip code:</strong>
  <%= @investor.zip_code %>
</p>

<ul>
  <% @investor.files.each do |file| %>
    <li>
    <% if file.previewable? %>
      <p>Download: <%= link_to file.filename, rails_blob_path(file, disposition: "attachment") %></p>
      <%= image_tag file.preview(resize: "100x100") %>
    <% elsif file.representable? %>
      <p>Download:<%= link_to file.filename, rails_blob_path(file, disposition: "attachment") %></p>
      <%= image_tag url_for(file) %>
    <% else %>
      <p>Preview Not Available </p>
    <% end %>
    </li>
  <% end %>
</ul>

<%= link_to 'Edit Investor', edit_investor_path(@investor) %> |
<%= link_to 'Back to All Investors', investors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PerpendicuarInvestments</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/startup/index.html.erb
<h1>Welcome to Perpendicular Investments</h1>

<%= link_to "Login", '/login', method: :get%> |
<%= link_to "Sign Up", '/users/new', method: :get%>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to "Back to Home", '/', method: :get%> 

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Your User Information</h1>
<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>


<%= link_to "Log out", logout_path, method: :delete %> | <%= link_to 'Edit User', edit_user_path(@user) %> | <%= link_to 'Destroy User', @user, method: :delete, data: { confirm: 'Are you sure? All  Investors associated with this User will also be deleted.' } %>

<h3>Your Investors</h3>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Dob</th>
      <th>Phone</th>
      <th>Street address</th>
      <th>State address</th>
      <th>Zip code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user.investors.each do |investor| %>
      <tr>
        <td><%= investor.first_name %></td>
        <td><%= investor.last_name %></td>
        <td><%= investor.dob %></td>
        <td><%= investor.phone %></td>
        <td><%= investor.street_address %></td>
        <td><%= investor.state_address %></td>
        <td><%= investor.zip_code %></td>
        <td><%= link_to 'Show', investor %></td>
        <td><%= link_to 'Edit', edit_investor_path(investor) %></td>
        <td><%= link_to 'Destroy', investor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Create New Investor', new_investor_path %>